apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
  namespace: operations
spec:
  containers:
  - name: registry
    image: registry:2.6.2
    volumeMounts:
    - mountPath: /var/lib/registry
      name: registry-data
  volumes:
  - name: registry-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: operations
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry-ingress
  namespace: operations
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: registry
    servicePort: 5000
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: registry-deployment
#   labels: 